# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadbVolume:/var/lib/mysql
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mariadbVolume: